- name: Config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop: [/etc/apt/keyrings, /etc/docker]

- name: Docker key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Docker repo
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.sources
    mode: "0644"
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/debian
      Suites: {{ ansible_facts['distribution_release'] }}
      Components: stable
      Signed-By: /etc/apt/keyrings/docker.asc

- name: Docker daemon config
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    mode: "0644"
    content: |
      {
        "storage-driver": "overlay2",
        "log-driver": "local"
      }
  notify: Restart docker

- name: Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    update_cache: true

- name: dockerd
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
