services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports: ["9090:9090"]
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=90d
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus:/prometheus

  pve-exporter:
    image: prompve/prometheus-pve-exporter:latest
    restart: unless-stopped
    volumes:
      - ./pve.yml:/etc/prometheus/pve.yml:ro

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports: ["3000:3000"]
    environment:
      TZ: America/Santiago
      GF_ANALYTICS_REPORTING_ENABLED: "false"
    volumes:
      - ./grafana:/etc/grafana/provisioning:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro
      - ./data/grafana:/var/lib/grafana
